version: '3.9'
services:
  backend:
    container_name: django-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USR=${DB_USR}
      - DB_PWD=${DB_PWD}
      # - DB_ROOT_PWD=${DB_ROOT_PWD}
      - DB_PORT_CONTAINER=${DB_PORT_CONTAINER}

  database:
    image: mysql:8.1
    container_name: mysql-docker
    restart: always
    ports:
      - "${DB_PORT_HOST}:${DB_PORT_CONTAINER}"  # host-facing:inside-container
    volumes:
      - .dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USR}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
