version: '20.10.23'
services:
  backend:
    container_name: django-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-docker
    restart: always
    ports:
      - ${DB_PORT_HOST}:${DB_PORT_CONTAINER}
    volumes:
      - .dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USR}
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
